---

# Variables here are applicable to all host groups
deploy_user: "{{ ansible_user }}"
status_dir: "{{ deploy_dir }}/status"
backup_dir: "{{ deploy_dir }}/backup"
images_dir: "{{ deploy_dir }}/images"

# Local
downloads_dir: "{{ playbook_dir }}/downloads"
resources_dir: "{{ playbook_dir }}/resources"
fetch_tmp_dir: "{{ playbook_dir }}/collect_diagnosis_data"
fetch_dir:     "{{ playbook_dir }}/collect_diagnosis"
cert_dir:      "{{ playbook_dir }}/conf/ssl"
script_dir:    "{{ playbook_dir }}/scripts"
binary_dir:    "{{ playbook_dir }}/resources/bin"
gz_dir:        "{{ playbook_dir }}/resources/gz"

# env
env_dir:        "/data1/bigdata/env" # TODO hidden danger
java_home:      "{{ env_dir }}/java/jdk-{{ java_version }}"
scala_home:     "{{ env_dir }}/scala/scala-{{ scala_version }}"

# bigdata
bigdata_dir: "/data1/bigdata" # TODO hidden danger
zookeeper_home: "{{ bigdata_dir }}/zookeeper/zookeeper-{{ zookeeper_version }}"
hadoop_home: "{{ bigdata_dir }}/hadoop/hadoop-{{ hadoop_version }}"
hive_home: "{{ bigdata_dir }}/hive/hive-{{ hive_version }}"
spark_home: "{{ bigdata_dir }}/spark/spark-{{ spark_version }}"
sqoop_home: "{{ bigdata_dir }}/sqoop/sqoop-{{ sqoop_version }}"

ds_home: "{{ deploy_dir }}/ds-{{ ds_version }}"


# default configuration for multiple host groups and roles
node_exporter_port: 9100
blackbox_exporter_port: 9115
kafka_exporter_port: 9308

# docker
docker_bin_dir: "/usr/bin"

# Random shifts for retrying failed ops like downloading
retry_stagger: 5

# deployment methods, [binary, docker] docker deployment method is not recommended and deprecated.
deployment_method: binary

enable_log_clean: False
log_retain_days: 28

dev_mode: False

# systemd: Specifies whether to send SIGKILL to remaining processes after a timeout.
disable_send_sigkill: False

# pump
pump_port: 8250
pump_data_dir: "{{ deploy_dir }}/data.pump"
pump_log_dir: "{{ deploy_dir }}/log"
pump_cert_dir: "{{ deploy_dir }}/conf/ssl"

# drainer
drainer_port: 8249
