---

- name: create related folders
  file: name={{ env_dir }}/scala state=directory mode=755

- name: install
  unarchive:
    src={{ gz_dir }}/scala-{{ scala_version }}.tar.gz
    dest={{ env_dir }}/scala/
    mode=755

- name: setting profile
  lineinfile: dest=/etc/profile state=present regexp={{ item.regexp }} line={{ item.line }}
  with_items:
    - { regexp: 'SCALA_HOME=', line: 'export SCALA_HOME={{ scala_home }}' }
    - { regexp: 'PATH=\$SCALA_HOME', line: 'export PATH=$SCALA_HOME/bin:$PATH' }

- name: source profile
  shell: "source /etc/profile"
