---

spark:
  spark.master: "yarn"
  spark.driver.memory: "4g"
  spark.executor.memory: "4g"
  spark.executor.memoryOverhead: "4g"
  spark.driver.maxResultSize: "12g"
  spark.debug.maxToStringFields: 200
  spark.eventLog.enabled: "true"
  spark.eventLog.dir: "hdfs:///user/spark/history/job_history_log"
  spark.eventLog.compress: "true"
  spark.shuffle.service.enabled: "true"
  spark.shuffle.service.port: 7337
  spark.dynamicAllocation.enabled: "true"
  spark.dynamicAllocation.minExecutors: 3
  spark.dynamicAllocation.maxExecutors: 70
  spark.port.maxRetries: 100
  spark.driver.extraLibraryPath: "{{ spark_home }}/jars/*"
  spark.driver.extraClassPath: "{{ spark_home }}/jars/*"
  spark.executor.extraLibraryPath: "{{ spark_home }}/jars/*"
  spark.executor.extraClassPath: "{{ spark_home }}/jars/*"
  spark.file: "file://{{ spark_home }}/conf/hdfs-site.xml,file://{{ spark_home }}/conf/core-site.xml"
  spark.yarn.archive: "hdfs:///spark/jar/spark-libs.jar"