---

alert:
  alert.type: "EMAIL"
  mail.protocol: "SMTP"
  mail.server.host: "xxx.xxx.com"
  mail.server.port: 25
  mail.sender: "xxx@xxx.com"
  mail.user: "xxx@xxx.com"
  mail.passwd: "111111"
  mail.smtp.starttls.enable: "true"
  mail.smtp.ssl.enable: "false"
  mail.smtp.ssl.trust: "xxx.xxx.com"
  enterprise.wechat.enable: "false"
  plugin.dir: "/Users/xx/your/path/to/plugin/dir"

api:
  server.port: 40000
  server.servlet.session.timeout: 7200
  server.servlet.context-path: "/dolphinscheduler/"
  spring.servlet.multipart.max-file-size: "1024MB"
  spring.servlet.multipart.max-request-size: "1024MB"
  server.jetty.max-http-post-size: "5000000"
  spring.messages.encoding: "UTF-8"
  spring.messages.basename: "i18n/messages"
  security.authentication.type: "PASSWORD"

common:
  resource.storage.type: "HDFS"
  resource.upload.path: "/dolphinscheduler"
  hadoop.security.authentication.startup.state: "false"
  java.security.krb5.conf.path: "/opt/krb5.conf"
  login.user.keytab.username: "hdfs-mycluster@ESZ.COM"
  login.user.keytab.path: "/opt/hdfs.headless.keytab"
  hdfs.root.user: "hdfs"
  fs.defaultFS: "hdfs://mycluster:8020"
  fs.s3a.endpoint: "http://192.168.xx.xx:9010"
  fs.s3a.access.key: "A3DXS30FO22544RE"
  fs.s3a.secret.key: "OloCLq3n+8+sdPHUhJ21XrSxTC+JK"
  yarn.resourcemanager.ha.rm.ids: "192.168.xx.xx,192.168.xx.xx"
  yarn.application.status.address: "http://ds1:8088/ws/v1/cluster/apps/%s"
  development.state: "false"
  kerberos.expire.time: 7

datasource:
  spring.datasource.driver-class-name: "com.mysql.jdbc.Driver"
  spring.datasource.url: "jdbc:mysql://localhost:3306/ds?characterEncoding=UTF-8&allowMultiQueries=true"
  spring.datasource.username: "ds"
  spring.datasource.password: "ds"

worker:
  worker.group: "default"

zookeeper:
  zookeeper.quorum: "{% for url in groups['zookeeper_servers'] %}{{ hostvars[url].ansible_host }}:2181{% if not loop.last %}{{','}}{% endif %}{% endfor %}"
